language: php

php:
  - 7.0.22


env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan key:generate

script: vendor/bin/phpunit
notifications:
  email: false

